import { createClient } from "@/lib/supabase/server";
import { NextRequest, NextResponse } from "next/server";
import { calculateCIReport } from "@/lib/ci/calculator";
import type { CIMethodology, CIDataQuality, CIEmissionInput } from "@/types/database";

// POST /api/ci-reports - Create a new CI report
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const body = await request.json();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Get supplier
    const { data: supplier } = await supabase
      .from("suppliers")
      .select("id")
      .eq("profile_id", user.id)
      .single();

    if (!supplier) {
      return NextResponse.json(
        { error: "Supplier not found" },
        { status: 404 }
      );
    }

    // Validate required fields
    const {
      feedstock_id,
      reporting_period_start,
      reporting_period_end,
      reference_year,
      methodology,
      methodology_version,
      data_quality_level = "default",
      scope1_cultivation = 0,
      scope1_processing = 0,
      scope1_transport = 0,
      scope2_electricity = 0,
      scope2_steam_heat = 0,
      scope3_upstream_inputs = 0,
      scope3_land_use_change = 0,
      scope3_distribution = 0,
      scope3_end_of_life = 0,
      calculation_notes,
      supporting_documents = [],
    } = body;

    if (!feedstock_id || !reporting_period_start || !reporting_period_end || !reference_year || !methodology) {
      return NextResponse.json(
        { error: "Missing required fields: feedstock_id, reporting_period_start, reporting_period_end, reference_year, methodology" },
        { status: 400 }
      );
    }

    // Verify feedstock belongs to supplier
    const { data: feedstock } = await supabase
      .from("feedstocks")
      .select("id, supplier_id, category")
      .eq("id", feedstock_id)
      .single();

    if (!feedstock) {
      return NextResponse.json(
        { error: "Feedstock not found" },
        { status: 404 }
      );
    }

    if (feedstock.supplier_id !== supplier.id) {
      return NextResponse.json(
        { error: "Not authorized to create CI report for this feedstock" },
        { status: 403 }
      );
    }

    // Calculate CI values using the engine
    const ciInput: CIEmissionInput = {
      scope1_cultivation,
      scope1_processing,
      scope1_transport,
      scope2_electricity,
      scope2_steam_heat,
      scope3_upstream_inputs,
      scope3_land_use_change,
      scope3_distribution,
      scope3_end_of_life,
    };

    const calculations = calculateCIReport(
      ciInput,
      methodology as CIMethodology,
      data_quality_level as CIDataQuality
    );

    // Create CI report (report_id is auto-generated by trigger)
    const { data, error } = await supabase
      .from("carbon_intensity_reports")
      .insert({
        feedstock_id,
        supplier_id: supplier.id,
        reporting_period_start,
        reporting_period_end,
        reference_year,
        methodology,
        methodology_version,
        data_quality_level,
        scope1_cultivation,
        scope1_processing,
        scope1_transport,
        scope2_electricity,
        scope2_steam_heat,
        scope3_upstream_inputs,
        scope3_land_use_change,
        scope3_distribution,
        scope3_end_of_life,
        ci_score: calculations.ci_score,
        uncertainty_range_low: calculations.uncertainty_range_low,
        uncertainty_range_high: calculations.uncertainty_range_high,
        calculation_notes,
        supporting_documents,
        status: "draft",
      })
      .select(`
        *,
        feedstock:feedstocks(id, feedstock_id, name, category)
      `)
      .single();

    if (error) {
      console.error("Error creating CI report:", error);
      return NextResponse.json(
        { error: "Failed to create CI report" },
        { status: 500 }
      );
    }

    // Create audit log entry
    await supabase.from("ci_audit_logs").insert({
      report_id: data.id,
      user_id: user.id,
      action: "created",
      new_status: "draft",
    });

    return NextResponse.json(data, { status: 201 });
  } catch (error) {
    console.error("Error in POST /api/ci-reports:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// GET /api/ci-reports - List CI reports
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { searchParams } = new URL(request.url);

    const role = searchParams.get("role"); // "supplier" or "auditor"
    const status = searchParams.get("status");
    const methodology = searchParams.get("methodology");
    const feedstockId = searchParams.get("feedstock_id");

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Get user profile to check role
    const { data: profile } = await supabase
      .from("profiles")
      .select("role")
      .eq("id", user.id)
      .single();

    let query = supabase
      .from("carbon_intensity_reports")
      .select(`
        *,
        feedstock:feedstocks(id, feedstock_id, name, category),
        supplier:suppliers(id, company_name),
        verifier:profiles!carbon_intensity_reports_verified_by_fkey(id, full_name)
      `)
      .order("created_at", { ascending: false });

    if (role === "supplier") {
      // Get supplier's reports
      const { data: supplier } = await supabase
        .from("suppliers")
        .select("id")
        .eq("profile_id", user.id)
        .single();

      if (!supplier) {
        return NextResponse.json(
          { error: "Supplier not found" },
          { status: 404 }
        );
      }

      query = query.eq("supplier_id", supplier.id);
    } else if (role === "auditor") {
      // Auditors can view all reports (or only assigned ones)
      if (!profile || !["auditor", "admin"].includes(profile.role)) {
        return NextResponse.json(
          { error: "Not authorized as auditor" },
          { status: 403 }
        );
      }
      // Don't filter - auditors see all
    } else if (role === "buyer") {
      // Buyers can only see verified reports
      query = query.eq("status", "verified");
    } else {
      return NextResponse.json(
        { error: "role parameter must be 'supplier', 'auditor', or 'buyer'" },
        { status: 400 }
      );
    }

    // Apply additional filters
    if (status) {
      query = query.eq("status", status);
    }
    if (methodology) {
      query = query.eq("methodology", methodology);
    }
    if (feedstockId) {
      query = query.eq("feedstock_id", feedstockId);
    }

    const { data, error } = await query;

    if (error) {
      console.error("Error fetching CI reports:", error);
      return NextResponse.json(
        { error: "Failed to fetch CI reports" },
        { status: 500 }
      );
    }

    return NextResponse.json(data);
  } catch (error) {
    console.error("Error in GET /api/ci-reports:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
