/**
 * Carbon Wallet Component
 * 
 * Displays carbon asset balances from Trovio CorTenX registry.
 * Enables growers to view ACCU/SMC/GO balances, retire units,
 * and track their environmental impact.
 */

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/badge';
import { Slider } from '@/components/ui/slider';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Separator } from '@/components/ui/separator';
import { Progress } from '@/components/ui/progress';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Leaf,
  TrendingUp,
  TrendingDown,
  Wallet,
  ArrowRight,
  ExternalLink,
  CheckCircle2,
  Clock,
  Car,
  Home,
  TreeDeciduous,
  Zap,
  RefreshCw,
  Shield,
  Award,
  Info,
  AlertCircle,
} from 'lucide-react';
import { trpc } from '@/lib/trpc';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

// ============================================================================
// TYPES
// ============================================================================

interface CarbonBalance {
  instrument: 'ACCU' | 'SMC' | 'GO' | 'LGC';
  available: number;
  locked: number;
  total: number;
}

interface CarbonPrice {
  instrument: string;
  spotPrice: number;
  change24h: number;
}

// ============================================================================
// CONSTANTS
// ============================================================================

const INSTRUMENT_INFO = {
  ACCU: {
    name: 'Australian Carbon Credit Unit',
    description: 'Each ACCU represents 1 tonne of CO₂ equivalent emissions avoided or removed.',
    color: 'text-green-600',
    bgColor: 'bg-green-100',
    icon: Leaf,
  },
  SMC: {
    name: 'Safeguard Mechanism Credit',
    description: 'Credits generated by facilities that reduce emissions below their baseline.',
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    icon: Shield,
  },
  GO: {
    name: 'Guarantee of Origin',
    description: 'Certificates that verify electricity came from renewable sources.',
    color: 'text-amber-600',
    bgColor: 'bg-amber-100',
    icon: Zap,
  },
  LGC: {
    name: 'Large-scale Generation Certificate',
    description: 'Certificates from large-scale renewable energy generation.',
    color: 'text-purple-600',
    bgColor: 'bg-purple-100',
    icon: Award,
  },
};

// ============================================================================
// SUB-COMPONENTS
// ============================================================================

function BalanceCard({ 
  balance, 
  price,
  onRetire,
}: { 
  balance: CarbonBalance; 
  price?: CarbonPrice;
  onRetire: (instrument: string, maxQty: number) => void;
}) {
  const info = INSTRUMENT_INFO[balance.instrument];
  const Icon = info.icon;
  const valueAud = price ? balance.available * price.spotPrice : null;
  
  return (
    <Card className={cn("relative overflow-hidden", balance.available > 0 && "border-l-4 border-l-green-500")}>
      <CardContent className="p-4">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className={cn("p-2 rounded-lg", info.bgColor)}>
              <Icon className={cn("h-5 w-5", info.color)} />
            </div>
            <div>
              <p className="font-semibold">{balance.instrument}</p>
              <Tooltip>
                <TooltipTrigger asChild>
                  <p className="text-xs text-muted-foreground cursor-help">{info.name}</p>
                </TooltipTrigger>
                <TooltipContent className="max-w-xs">
                  <p>{info.description}</p>
                </TooltipContent>
              </Tooltip>
            </div>
          </div>
          
          {price && (
            <div className="text-right">
              <p className="text-sm font-medium">${(price.spotPrice ?? price.priceAud ?? 0).toFixed(2)}</p>
              <p className={cn(
                "text-xs flex items-center gap-1",
                (price.change24h ?? 0) >= 0 ? "text-green-600" : "text-red-600"
              )}>
                {(price.change24h ?? 0) >= 0 ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
                {(price.change24h ?? 0) >= 0 ? '+' : ''}{(price.change24h ?? 0).toFixed(2)}%
              </p>
            </div>
          )}
        </div>
        
        <div className="mt-4 grid grid-cols-3 gap-2 text-center">
          <div>
            <p className="text-2xl font-bold">{(balance.available ?? 0).toLocaleString()}</p>
            <p className="text-xs text-muted-foreground">Available</p>
          </div>
          <div>
            <p className="text-lg text-muted-foreground">{(balance.locked ?? 0).toLocaleString()}</p>
            <p className="text-xs text-muted-foreground">Locked</p>
          </div>
          <div>
            <p className="text-lg text-muted-foreground">{(balance.total ?? 0).toLocaleString()}</p>
            <p className="text-xs text-muted-foreground">Total</p>
          </div>
        </div>
        
        {valueAud && valueAud > 0 && (
          <div className="mt-3 pt-3 border-t">
            <p className="text-sm text-muted-foreground">
              Portfolio value: <span className="font-semibold text-foreground">${(valueAud ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
            </p>
          </div>
        )}
        
        {(balance.available ?? 0) > 0 && (
          <Button 
            variant="outline" 
            size="sm" 
            className="w-full mt-3"
            onClick={() => onRetire(balance.instrument, balance.available)}
          >
            Retire Units
            <ArrowRight className="h-4 w-4 ml-2" />
          </Button>
        )}
      </CardContent>
    </Card>
  );
}

function ImpactTicker({ stats }: { 
  stats: { 
    totalRetired: number; 
    equivalents: { 
      carsOffRoad: number; 
      householdsOffset: number; 
      treesEquivalent: number; 
    };
  };
}) {
  return (
    <Card className="bg-gradient-to-r from-green-50 to-emerald-50 border-green-200">
      <CardContent className="p-4">
        <div className="flex items-center gap-2 mb-3">
          <CheckCircle2 className="h-5 w-5 text-green-600" />
          <p className="font-semibold text-green-800">Your Environmental Impact</p>
        </div>
        
        <p className="text-lg text-green-700 mb-4">
          You have permanently retired{' '}
          <span className="font-bold text-2xl">{(stats.totalRetired ?? 0).toLocaleString()}</span>{' '}
          t CO₂e
        </p>
        
        <div className="grid grid-cols-3 gap-4 text-center">
          <div className="p-2 rounded-lg bg-white/60">
            <Car className="h-6 w-6 mx-auto text-green-600 mb-1" />
            <p className="text-lg font-bold text-green-800">{stats.equivalents?.carsOffRoad ?? 0}</p>
            <p className="text-xs text-green-600">cars off road/yr</p>
          </div>
          <div className="p-2 rounded-lg bg-white/60">
            <Home className="h-6 w-6 mx-auto text-green-600 mb-1" />
            <p className="text-lg font-bold text-green-800">{stats.equivalents?.householdsOffset ?? 0}</p>
            <p className="text-xs text-green-600">households offset</p>
          </div>
          <div className="p-2 rounded-lg bg-white/60">
            <TreeDeciduous className="h-6 w-6 mx-auto text-green-600 mb-1" />
            <p className="text-lg font-bold text-green-800">{(stats.equivalents?.treesEquivalent ?? 0).toLocaleString()}</p>
            <p className="text-xs text-green-600">trees equivalent</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

function RetireDialog({ 
  open, 
  onOpenChange, 
  instrument, 
  maxQty,
  onRetire,
  isLoading,
}: { 
  open: boolean;
  onOpenChange: (open: boolean) => void;
  instrument: string;
  maxQty: number;
  onRetire: (data: { instrument: string; quantity: number; narrative: string }) => void;
  isLoading: boolean;
}) {
  const [quantity, setQuantity] = useState(Math.min(100, maxQty));
  const [narrative, setNarrative] = useState('');
  
  const handleRetire = () => {
    if (quantity <= 0 || quantity > maxQty) {
      toast.error('Invalid quantity');
      return;
    }
    if (narrative.length < 10) {
      toast.error('Please provide a retirement narrative (min 10 characters)');
      return;
    }
    onRetire({ instrument, quantity, narrative });
  };
  
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Leaf className="h-5 w-5 text-green-600" />
            Retire {instrument} Units
          </DialogTitle>
          <DialogDescription>
            Permanently retire carbon units. This action cannot be undone.
          </DialogDescription>
        </DialogHeader>
        
        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <div className="flex justify-between">
              <Label>Quantity to Retire</Label>
              <span className="text-sm text-muted-foreground">Max: {(maxQty ?? 0).toLocaleString()}</span>
            </div>
            <div className="flex items-center gap-4">
              <Slider
                value={[quantity]}
                min={1}
                max={maxQty}
                step={1}
                onValueChange={(v) => setQuantity(v[0])}
                className="flex-1"
              />
              <Input
                type="number"
                value={quantity}
                onChange={(e) => setQuantity(Math.min(maxQty, Math.max(1, parseInt(e.target.value) || 1)))}
                className="w-24"
              />
            </div>
          </div>
          
          <div className="space-y-2">
            <Label>Retirement Narrative</Label>
            <Textarea
              placeholder="e.g., Retired on behalf of [Company Name] for [Project/Delivery Reference]"
              value={narrative}
              onChange={(e) => setNarrative(e.target.value)}
              rows={3}
            />
            <p className="text-xs text-muted-foreground">
              This narrative will appear on the public retirement certificate.
            </p>
          </div>
          
          <div className="p-3 rounded-lg bg-amber-50 border border-amber-200">
            <div className="flex items-start gap-2">
              <AlertCircle className="h-4 w-4 text-amber-600 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-amber-800">Permanent Action</p>
                <p className="text-xs text-amber-600">
                  Retired units are permanently removed from circulation and cannot be recovered.
                </p>
              </div>
            </div>
          </div>
        </div>
        
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button 
            onClick={handleRetire}
            disabled={isLoading || quantity <= 0 || narrative.length < 10}
            className="bg-green-600 hover:bg-green-700"
          >
            {isLoading ? (
              <>
                <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                Processing...
              </>
            ) : (
              <>
                <CheckCircle2 className="h-4 w-4 mr-2" />
                Retire {(quantity ?? 0).toLocaleString()} Units
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function TransactionHistory({ userId }: { userId?: number }) {
  const { data: historyData, isLoading } = trpc.carbon.history.useQuery({ limit: 10 });
  
  if (isLoading) {
    return (
      <div className="space-y-2">
        {[1, 2, 3].map((i) => (
          <div key={i} className="h-16 bg-muted animate-pulse rounded-lg" />
        ))}
      </div>
    );
  }
  
  const transactions = historyData?.transactions || [];
  
  if (transactions.length === 0) {
    return (
      <div className="text-center py-8 text-muted-foreground">
        <Clock className="h-8 w-8 mx-auto mb-2 opacity-50" />
        <p>No transactions yet</p>
      </div>
    );
  }
  
  return (
    <div className="space-y-2">
      {transactions.map((txn) => (
        <div 
          key={txn.id}
          className="flex items-center justify-between p-3 rounded-lg border bg-card hover:bg-muted/50 transition-colors"
        >
          <div className="flex items-center gap-3">
            <div className={cn(
              "p-2 rounded-full",
              txn.txnType === 'IN' && "bg-green-100",
              txn.txnType === 'OUT' && "bg-red-100",
              txn.txnType === 'RETIRE' && "bg-blue-100",
              txn.txnType === 'BUNDLE_LOCK' && "bg-purple-100",
            )}>
              {txn.txnType === 'IN' && <TrendingUp className="h-4 w-4 text-green-600" />}
              {txn.txnType === 'OUT' && <TrendingDown className="h-4 w-4 text-red-600" />}
              {txn.txnType === 'RETIRE' && <CheckCircle2 className="h-4 w-4 text-blue-600" />}
              {txn.txnType === 'BUNDLE_LOCK' && <Shield className="h-4 w-4 text-purple-600" />}
            </div>
            <div>
              <p className="font-medium">
                {txn.txnType === 'IN' && 'Received'}
                {txn.txnType === 'OUT' && 'Transferred'}
                {txn.txnType === 'RETIRE' && 'Retired'}
                {txn.txnType === 'BUNDLE_LOCK' && 'Locked in Bundle'}
                {' '}{(txn.quantity ?? 0).toLocaleString()} {txn.instrument}
              </p>
              <p className="text-xs text-muted-foreground">
                {new Date(txn.createdAt).toLocaleDateString()}
              </p>
            </div>
          </div>
          
          {txn.registryUrl && (
            <Button variant="ghost" size="sm" asChild>
              <a href={txn.registryUrl} target="_blank" rel="noopener noreferrer">
                <ExternalLink className="h-4 w-4" />
              </a>
            </Button>
          )}
        </div>
      ))}
    </div>
  );
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export function CarbonWallet() {
  const [retireDialogOpen, setRetireDialogOpen] = useState(false);
  const [selectedInstrument, setSelectedInstrument] = useState<string>('ACCU');
  const [selectedMaxQty, setSelectedMaxQty] = useState(0);
  
  // Queries
  const { data: walletData, isLoading: walletLoading } = trpc.carbon.hasWallet.useQuery();
  const { data: balanceData, isLoading: balanceLoading, refetch: refetchBalance } = trpc.carbon.balance.useQuery(
    undefined,
    { enabled: walletData?.connected || walletData?.hasWallet }
  );
  const { data: pricesData } = trpc.carbon.prices.useQuery();
  const { data: impactData } = trpc.carbon.impactStats.useQuery(
    undefined,
    { enabled: walletData?.connected || walletData?.hasWallet }
  );
  
  // Mutations
  const retireMutation = trpc.carbon.retire.useMutation({
    onSuccess: (data) => {
      toast.success(
        <div>
          <p className="font-semibold">Units Retired Successfully!</p>
          <p className="text-sm">{data.quantity} {data.instrument} permanently retired.</p>
          <a 
            href={data.certificateUrl} 
            target="_blank" 
            rel="noopener noreferrer"
            className="text-sm text-blue-600 hover:underline flex items-center gap-1 mt-1"
          >
            View Certificate <ExternalLink className="h-3 w-3" />
          </a>
        </div>
      );
      setRetireDialogOpen(false);
      refetchBalance();
    },
    onError: (error) => {
      toast.error(`Retirement failed: ${error.message}`);
    },
  });
  
  const handleOpenRetire = (instrument: string, maxQty: number) => {
    setSelectedInstrument(instrument);
    setSelectedMaxQty(maxQty);
    setRetireDialogOpen(true);
  };
  
  const handleRetire = (data: { instrument: string; quantity: number; narrative: string }) => {
    retireMutation.mutate({
      instrument: data.instrument as 'ACCU' | 'SMC' | 'GO' | 'LGC',
      quantity: data.quantity,
      beneficiaryName: 'ABFI Grower', // Would come from user profile
      narrative: data.narrative,
    });
  };
  
  const isLoading = walletLoading || balanceLoading;
  
  // Normalize balance data to handle both old and new API structures
  const normalizedBalances = (() => {
    if (!balanceData) return null;
    
    // New structure: { balances: [...] }
    if (balanceData.balances && Array.isArray(balanceData.balances)) {
      return balanceData.balances;
    }
    
    // Old structure: { accu: {...}, smc: {...}, go: {...}, lgc: {...} }
    const oldData = balanceData as any;
    const instruments = ['accu', 'smc', 'go', 'lgc'];
    const balances: CarbonBalance[] = [];
    
    for (const inst of instruments) {
      if (oldData[inst]) {
        balances.push({
          instrument: inst.toUpperCase() as 'ACCU' | 'SMC' | 'GO' | 'LGC',
          available: oldData[inst].balance || 0,
          locked: 0,
          total: oldData[inst].balance || 0,
        });
      }
    }
    
    return balances.length > 0 ? balances : null;
  })();
  
  // Check if wallet is connected (handle both old and new API)
  const isWalletConnected = walletData?.connected ?? walletData?.hasWallet ?? false;
  
  // Price lookup helper
  const getPrice = (instrument: string) => {
    if (!pricesData) return undefined;
    
    // New structure: { prices: [...] }
    if (pricesData.prices && Array.isArray(pricesData.prices)) {
      return pricesData.prices.find(p => p.instrument === instrument);
    }
    
    // Old structure: array directly
    if (Array.isArray(pricesData)) {
      return (pricesData as any[]).find(p => p.instrument === instrument);
    }
    
    return undefined;
  };
  
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-green-100">
            <Wallet className="h-6 w-6 text-green-600" />
          </div>
          <div>
            <h2 className="text-xl font-bold">Carbon Wallet</h2>
            <p className="text-sm text-muted-foreground">
              Powered by Clean Energy Regulator (CorTenX)
            </p>
          </div>
        </div>
        
        {isWalletConnected && (
          <Badge variant="outline" className="gap-1 text-green-600 border-green-300">
            <CheckCircle2 className="h-3 w-3" />
            Connected
          </Badge>
        )}
      </div>
      
      {/* Impact Stats */}
      {impactData && impactData.totalRetired > 0 && (
        <ImpactTicker stats={impactData} />
      )}
      
      {/* Tabs */}
      <Tabs defaultValue="balances">
        <TabsList>
          <TabsTrigger value="balances">Balances</TabsTrigger>
          <TabsTrigger value="history">History</TabsTrigger>
        </TabsList>
        
        <TabsContent value="balances" className="mt-4">
          {isLoading ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {[1, 2, 3, 4].map((i) => (
                <div key={i} className="h-48 bg-muted animate-pulse rounded-lg" />
              ))}
            </div>
          ) : normalizedBalances && normalizedBalances.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {normalizedBalances.map((balance) => (
                <BalanceCard
                  key={balance.instrument}
                  balance={balance}
                  price={getPrice(balance.instrument)}
                  onRetire={handleOpenRetire}
                />
              ))}
            </div>
          ) : (
            <Card>
              <CardContent className="p-8 text-center">
                <Wallet className="h-12 w-12 mx-auto mb-4 text-muted-foreground opacity-50" />
                <h3 className="text-lg font-semibold mb-2">Connect Your Carbon Wallet</h3>
                <p className="text-muted-foreground mb-4">
                  Link your CER account to view and manage your carbon assets directly from ABFI.
                </p>
                <Button className="bg-green-600 hover:bg-green-700">
                  Verify Carbon Assets
                </Button>
              </CardContent>
            </Card>
          )}
          
          {/* Portfolio Summary */}
          {balanceData && (balanceData.portfolioValueAud || balanceData.totalValueAud) && (
            <Card className="mt-4">
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Total Portfolio Value</p>
                    <p className="text-2xl font-bold">
                      ${(balanceData.portfolioValueAud ?? balanceData.totalValueAud ?? 0).toLocaleString(undefined, { 
                        minimumFractionDigits: 2, 
                        maximumFractionDigits: 2 
                      })}
                    </p>
                  </div>
                  {balanceData.lastUpdated && (
                    <div className="text-right">
                      <p className="text-xs text-muted-foreground">Last updated</p>
                      <p className="text-sm">
                        {new Date(balanceData.lastUpdated).toLocaleTimeString()}
                      </p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}
        </TabsContent>
        
        <TabsContent value="history" className="mt-4">
          <TransactionHistory />
        </TabsContent>
      </Tabs>
      
      {/* Retire Dialog */}
      <RetireDialog
        open={retireDialogOpen}
        onOpenChange={setRetireDialogOpen}
        instrument={selectedInstrument}
        maxQty={selectedMaxQty}
        onRetire={handleRetire}
        isLoading={retireMutation.isPending}
      />
    </div>
  );
}

export default CarbonWallet;
